language: perl
dist: bionic
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
perl:
  - "5.28"
  - "5.26"
# Trigger a push build on master and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
addons:
  apt:
    update: true
    packages:
      - perl-doc
      - ctags
      - perltidy
branches:
  only:
    - master
    - /^dependabot.*$/
install:
  - curl -L http://cpanmin.us | sudo perl - App::cpanminus
  - sudo cpanm --quiet --notest Perl::Critic@1.132 CPAN::Uploader@0.103013 Devel::Cover@1.30
script:
  - ./scripts/coverage.sh
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm prune
        - travis_retry npm i
        - npx semantic-release