language: perl
dist: bionic
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
cache:
  directories:
  - "~/.npm"
  - "node_modules"
perl:
  - "5.28"
  - "5.26"
# Trigger a push build on master and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^dependabot.*$/
script:
  - ./scripts/coverage.sh
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm prune
        - travis_retry npm i
        - npx semantic-release