language: perl
dist: bionic
notifications:
  email:
    recipients:
      - kschwarz@hexonet.net
    on_success: never
    on_failure: always
perl:
  #see: http://www.cpan.org/src/
  - "5.30"
  #- "5.32" n/a yet
addons:
  apt:
    update: true
    packages:
      - perl-doc
      - ctags
      - perltidy
install:
  - cpanm --quiet --notest Perl::Critic@1.138 CPAN::Uploader@0.103014 Devel::Cover@1.36
  - cpanm -v --installdeps --notest .
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - npm prune
  - travis_retry npm i
script:
  - ./scripts/coverage.sh && ./scripts/perltidy.sh
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npx semantic-release
