name: Release
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "perl v5.30"

    container:
      image: perldocker/perl-tester:5.30

    steps:
      - uses: actions/checkout@v2
      - run: |
          apt install perl-doc ctags perltidy
      - name: install perl dependencies
        uses: perl-actions/install-with-cpanm@v1
        with:
          cpanfile: "cpanfile"
          sudo: false
          args: "--quiet --notest"
      - name: install perl-sdk sources as perl dependency
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: "."
          sudo: false
          args: "-v --installdeps --notest ."
      - run: |
          ./scripts/coverage.sh
          ./scripts/perltidy.sh
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          apt install perl-doc ctags perltidy
      - name: install perl dependencies
        uses: perl-actions/install-with-cpanm@v1
        with:
          cpanfile: "cpanfile"
          sudo: false
          args: "-v --quiet --notest"
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          npm prune && npm i
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CPAN_USER: ${{ secrets.CPAN_USER }}
          CPAN_PASSWORD: ${{ secrets.CPAN_PASSWORD }}
        run: npx semantic-release
