name: Release
on: 
  # will run for every branch, except tags. See RSRMID-206.
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - "**"
    # Sequence of patterns matched against refs/tags
    tags-ignore: 
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore: 
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: "perl v${{ matrix.perl-version }}"
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.32"
          - "5.30"

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - run: |
          apt install perl-doc ctags perltidy
      - name: install perl dependencies
        uses: perl-actions/install-with-cpanm@v1
        with:
          cpanfile: "cpanfile"
          sudo: false
          args: "--quiet --notest"
      - name: install perl-sdk sources as perl dependency
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: "."
          sudo: false
          args: "-v --installdeps --notest ."
      - run: |
          ./scripts/coverage.sh
          ./scripts/perltidy.sh
  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    container:
      image: perldocker/perl-tester:5.32

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          apt install perl-doc ctags perltidy
      - name: install perl dependencies
        uses: perl-actions/install-with-cpanm@v1
        with:
          cpanfile: "cpanfile"
          sudo: false
          args: "-v --quiet --notest"
      - name: install perl-sdk sources as perl dependency
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: "."
          sudo: false
          args: "-v --installdeps --notest ."
      - name: Setup NodeJS LTS
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
      - name: Install dependencies
        run: |
          node -v
          npm prune && npm i
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CPAN_USER: ${{ secrets.CPAN_USER }}
          CPAN_PASSWORD: ${{ secrets.CPAN_PASSWORD }}
        run: npx semantic-release
