name: Release
on:
  # will run for every branch, except tags. See RSRMID-206.
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - "master"

jobs:
  release:
    name: Release @ Perl LTS
    runs-on: ubuntu-latest

    container:
      image: perldocker/perl-tester:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: "npm"
      - name: APT Packages
        run: apt install -y perl-doc ctags perltidy lsb-release
      - name: SW Versions
        run: |
          lsb_release -a
          node -v
          npm -v
          perl -V
      - name: install perl dependencies
        run: |
          cpm install -g --no-test --show-build-log-on-failure --cpanfile cpanfile
          perl Makefile.PL
          make
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CPAN_USER: ${{ secrets.CPAN_USER }}
          CPAN_PASSWORD: ${{ secrets.CPAN_PASSWORD }}
        # we are root as of perl-tester image, npx won't invoke with root rights
        run: ./node_modules/.bin/semantic-release
